GET http://localhost:3001

###

GET http://localhost:3001/auth/login

###

GET http://localhost:3001/auth/register

### 

POST http://localhost:3001/auth/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODY1MTM0OTAxZjlkNGNlOTJlN2ZkMDYiLCJpYXQiOjE3NTE0NTQ1Mzd9.5uE_eWDLYEFeQhEkQ6ed-yvoUQ-QVXVAQXDpzdL7Fjo

{
  "username": "register nquanna",
  "password": "dzai"
}

### 

POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "register nquanna",
  "password": "dzai",
  "confirmPassword": "dzai"
}

###

POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "username": "register nquanna testing",
  "password": "dzai",
  "confirmPassword": "dzai"
}

### 

POST http://localhost:3001/auth/send-otp
Content-Type: application/json

{
  "email": "quanhm153@gmail.com"
} 

### 

POST http://localhost:3001/auth/forgot-password
Content-Type: application/json

{
  "email": "quanhm153@gmail.com",
  "otp": "841392"
}

### 

POST https://localhost:3001/auth/logout
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODdhODcwYTNmN2I2MzVhZDk1NWY5YWYiLCJpYXQiOjE3NTI4NjA0Mjh9.477DGHT68rC0GsJ9SaZAd5nNKC3kXCxQBguawzuZ7Jo