name = "firstapp"

main = "./src/index.js"       

compatibility_date = "2025-07-19"

account_id = "275dc838e99c4da3d38828103e185728"

workers_dev = true

# Nếu deploy custom domain thì điền route + zone_id,
# nếu k thì bỏ trống hoặc comment đi
# route = "example.com/*"
# zone_id = "YOUR_ZONE_ID"

[build]
# wrangler v3 auto dùng esbuild khi có `upload.format = "modules"`
# command = "npm install && npm run build"

[build.upload]
# format modules để wrangler bundle
# dir = "dist"
format = "service-worker"
